### ISSUE TITLE
Tailwind 2.2 build broken since tailwind v3 release out this week.

### ISSUE THREAD

**Issue by muhdammar** [BamButz/msbuild-extensions#14]
My minified css broken since my class used version 2+. I found your code, u get tailwind version "latest" in package.json. so I suspect that error come from the package.json since it will take latest tailwind v3.

**Comment by BamButz** [comment]
I will take a look at it later the day.

**Comment by BamButz** [comment]
I've now looked at it, I'm thinking of a method to install a fallback switch so that you can switch back to version 2.

As a temporary workaround, you could adapt the package.json in your NuGet packages and then delete the package-lock.json and the node_modules directory.
